version: '3.6'
services:
  redis:
    image: 'redis:alpine'
    hostname: redis
    ports:
      - '6379:6379'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
